const DEFAULT_DATA = {
  teams: [
    { id: 't1', name: 'Maya & Nia', short: 'MN', players: 'Maya Chen · Nia Kapoor', pool: 'A' },
    { id: 't2', name: 'Leo & Tomas', short: 'LT', players: 'Leo Martin · Tomas Reed', pool: 'A' },
    { id: 't3', name: 'Aisha & Bea', short: 'AB', players: 'Aisha Khan · Bea Olsen', pool: 'A' },
    { id: 't4', name: 'Owen & Kai', short: 'OK', players: 'Owen Wells · Kai Tan', pool: 'A' },
    { id: 't5', name: 'Zoe & Isla', short: 'ZI', players: 'Zoe Park · Isla Moore', pool: 'B' },
    { id: 't6', name: 'Finn & Arun', short: 'FA', players: 'Finn Cole · Arun Mehta', pool: 'B' },
    { id: 't7', name: 'Cleo & Sam', short: 'CS', players: 'Cleo James · Sam Hall', pool: 'B' },
    { id: 't8', name: 'Noah & Jules', short: 'NJ', players: 'Noah Grant · Jules Perry', pool: 'B' }
  ],
  matches: [
    { id: 'm1', pool: 'A', court: 'Court 1', time: '09:00', a: 't1', b: 't2', status: 'complete', games: [[21, 16]] },
    { id: 'm2', pool: 'A', court: 'Court 2', time: '09:00', a: 't3', b: 't4', status: 'complete', games: [[18, 21]] },
    { id: 'm3', pool: 'B', court: 'Court 3', time: '09:00', a: 't5', b: 't6', status: 'complete', games: [[21, 12]] },
    { id: 'm4', pool: 'B', court: 'Court 4', time: '09:00', a: 't7', b: 't8', status: 'complete', games: [[21, 17]] },
    { id: 'm5', pool: 'A', court: 'Court 2', time: '10:15', a: 't1', b: 't3', status: 'live', games: [] },
    { id: 'm6', pool: 'A', court: 'Court 1', time: '10:15', a: 't2', b: 't4', status: 'upcoming', games: [] },
    { id: 'm7', pool: 'B', court: 'Court 4', time: '10:15', a: 't5', b: 't7', status: 'live', games: [] },
    { id: 'm8', pool: 'B', court: 'Court 3', time: '10:15', a: 't6', b: 't8', status: 'upcoming', games: [] },
    { id: 'm9', pool: 'A', court: 'Court 1', time: '11:30', a: 't1', b: 't4', status: 'upcoming', games: [] },
    { id: 'm10', pool: 'A', court: 'Court 2', time: '11:30', a: 't2', b: 't3', status: 'upcoming', games: [] },
    { id: 'm11', pool: 'B', court: 'Court 3', time: '11:30', a: 't5', b: 't8', status: 'upcoming', games: [] },
    { id: 'm12', pool: 'B', court: 'Court 4', time: '11:30', a: 't6', b: 't7', status: 'upcoming', games: [] }
  ],
  tournament: { name: 'Friendly doubles,', date: 'Saturday, 21 September · 09:00', venue: 'Rally Club Courts', format: 'teams' },
  players: [], rotation: null, requests: [], approved: [], role: 'visitor', scorerName: ''
};
let data = loadData();
let activePool = 'A'; let activeFilter = 'all'; let editingMatchId = null;
const $ = (s) => document.querySelector(s);
const $$ = (s) => [...document.querySelectorAll(s)];
function loadData(){ try { const saved=JSON.parse(localStorage.getItem('rally-club-tournament')); return saved?{...structuredClone(DEFAULT_DATA),...saved,tournament:{...DEFAULT_DATA.tournament,...saved.tournament}}:structuredClone(DEFAULT_DATA); } catch { return structuredClone(DEFAULT_DATA); } }
function save(){ localStorage.setItem('rally-club-tournament', JSON.stringify(data)); }
function team(id){ return data.teams.find(t => t.id === id); }
function initials(name){ return name.split(' ').map(p => p[0]).join('').slice(0,2).toUpperCase(); }
function isRotation(){ return data.tournament.format==='rotation'; }
function player(id){ return data.players.find(p=>p.id===id); }
function rotationMatches(){ return data.rotation?.rounds.flatMap(round=>round.groups.flatMap(group=>group.matches.map(match=>({...match,round:round.number,group:group.name}))))||[]; }
function rotationMatchById(id){ return data.rotation?.rounds.flatMap(round=>round.groups.flatMap(group=>group.matches)).find(match=>match.id===id); }
function rotationMatchDetails(id){ return rotationMatches().find(match=>match.id===id); }
function rotationPair(ids){ return ids.map(id=>player(id)?.name||'TBD').join(' & '); }
function shuffle(items){ return [...items].sort(()=>Math.random()-.5); }
function buildRotationGroupMatches(ids,roundNumber,groupIndex){
  const pairings=[[[0,1],[2,3]],[[0,2],[1,3]],[[0,3],[1,2]]];
  return pairings.map((pairs,index)=>({id:`r${roundNumber}g${groupIndex+1}m${index+1}`,a:pairs[0].map(i=>ids[i]),b:pairs[1].map(i=>ids[i]),status:'upcoming',games:[],slot:index+1}));
}
function buildRotationRound(number,groups){ const placement=['1st-place group','2nd-place group','3rd-place group','4th-place group']; return {number,groups:groups.map((ids,index)=>({id:`r${number}g${index+1}`,name:number===1?`Group ${String.fromCharCode(65+index)}`:placement[index],playerIds:ids,matches:buildRotationGroupMatches(ids,number,index)}))}; }
function rotationRoundScores(round,group){
  const scores=group.playerIds.map(id=>({player:player(id),score:0,wins:0,played:0}));
  group.matches.filter(match=>match.status==='complete').forEach(match=>{ const aScore=scores.filter(row=>match.a.includes(row.player.id)), bScore=scores.filter(row=>match.b.includes(row.player.id)); const aGames=match.games.filter(([a,b])=>a>b).length,bGames=match.games.filter(([a,b])=>b>a).length; const aPoints=match.games.reduce((sum,[a])=>sum+a,0),bPoints=match.games.reduce((sum,[,b])=>sum+b,0); aScore.forEach(row=>{row.played++;row.score+=aPoints;if(aGames>bGames)row.wins++;});bScore.forEach(row=>{row.played++;row.score+=bPoints;if(bGames>aGames)row.wins++;}); });
  return scores.sort((a,b)=>b.score-a.score||b.wins-a.wins||a.player.name.localeCompare(b.player.name));
}
function rotationOverallScores(){ const scores=data.players.map(person=>({player:person,score:0,wins:0,played:0})); rotationMatches().filter(match=>match.status==='complete').forEach(match=>{ const aRows=scores.filter(row=>match.a.includes(row.player.id)),bRows=scores.filter(row=>match.b.includes(row.player.id)); const aGames=match.games.filter(([a,b])=>a>b).length,bGames=match.games.filter(([a,b])=>b>a).length,aPoints=match.games.reduce((sum,[a])=>sum+a,0),bPoints=match.games.reduce((sum,[,b])=>sum+b,0); aRows.forEach(row=>{row.played++;row.score+=aPoints;if(aGames>bGames)row.wins++;});bRows.forEach(row=>{row.played++;row.score+=bPoints;if(bGames>aGames)row.wins++;}); }); return scores.sort((a,b)=>b.score-a.score||b.wins-a.wins||a.player.name.localeCompare(b.player.name)); }
function rotationRoundComplete(round){ return round.groups.every(group=>group.matches.every(match=>match.status==='complete')); }
function advanceRotation(){ const rounds=data.rotation.rounds; const current=rounds[rounds.length-1]; if(!rotationRoundComplete(current)||rounds.length>=3)return null; const groups=current.groups.map(group=>rotationRoundScores(current,group).map(row=>row.player.id)); const nextGroups=[0,1,2,3].map(rank=>groups.map(group=>group[rank])); const next=buildRotationRound(rounds.length+1,nextGroups); rounds.push(next); return next; }
function teamBlock(t, reverse=false){ return `<div class="team-block ${reverse?'reverse':''}"><span class="team-avatar">${t.short}</span><div class="team-names">${t.name}<small>${t.players}</small></div></div>`; }
function matchWinner(match){ if(!match.games?.length) return null; let a=0,b=0; match.games.forEach(([x,y]) => x>y ? a++ : y>x ? b++ : null); return a===b ? null : a>b ? match.a : match.b; }
function scoreString(match){ return match.games?.map(([a,b])=>`${a}–${b}`).join('  ') || '—'; }
function standings(pool){
  const rows = data.teams.filter(t=>t.pool===pool).map(t=>({team:t,played:0,wins:0,losses:0,for:0,against:0}));
  data.matches.filter(m=>m.pool===pool && m.status==='complete').forEach(m=>{ const ra=rows.find(r=>r.team.id===m.a), rb=rows.find(r=>r.team.id===m.b); const win=matchWinner(m); ra.played++;rb.played++; if(win===m.a){ra.wins++;rb.losses++;}else if(win===m.b){rb.wins++;ra.losses++;} m.games.forEach(([a,b])=>{ra.for+=a;ra.against+=b;rb.for+=b;rb.against+=a;}); });
  return rows.sort((x,y)=>y.wins-x.wins || (y.for-y.against)-(x.for-x.against) || y.for-x.for);
}
function renderNext(){
  if(isRotation()){ const m=rotationMatches().find(match=>match.status==='upcoming'); if(!m){$('#nextMatch').innerHTML='<p class="rotation-ready">All three rounds are complete. See the leaderboard below.</p>';return;} $('#nextMatch').innerHTML=`<div class="next-match rotation-next"><div class="rotation-pair"><span>${rotationPair(m.a)}</span><small>Round ${m.round} · ${m.group}</small></div><div class="versus">VS<br><small>ROTATION ${m.slot}</small></div><div class="rotation-pair reverse"><span>${rotationPair(m.b)}</span><small>Round ${m.round} · ${m.group}</small></div></div>`; return; }
  const m = data.matches.find(m=>m.status==='live') || data.matches.find(m=>m.status==='upcoming'); if(!m) return; $('#nextMatch').innerHTML=`<div class="next-match">${teamBlock(team(m.a))}<div class="versus">VS<br><small>POOL ${m.pool}</small></div>${teamBlock(team(m.b),true)}</div>`;
}
function renderStats(){ const matches=isRotation()?rotationMatches():data.matches, target=isRotation()?36:matches.length, done=matches.filter(m=>m.status==='complete').length, left=target-done; $('#playedCount').textContent=done; $('#remainingCount').textContent=left; $('#liveStatus').textContent=isRotation()?`Round ${data.rotation.rounds.length} of 3`:`${matches.filter(m=>m.status==='live').length} courts live`; }
function renderFixtures(){
  if(isRotation()){ renderRotationFixtures(); return; }
  $('#fixtureFormatNote').textContent='1 game · 21 points';
  const statusCopy={live:'LIVE NOW',upcoming:'UP NEXT',complete:'PLAYED'};
  $('#fixturesList').innerHTML=data.matches.map(m=>{const a=team(m.a),b=team(m.b),allowed=canEdit(); return `<article class="fixture-item ${m.status}" data-status="${m.status}" ${activeFilter!=='all'&&m.status!==activeFilter?'hidden':''}><div class="fixture-meta"><b>${statusCopy[m.status]}</b>${m.time}<br>${m.court}</div><div class="fixture-teams"><div class="fixture-team"><span class="name"><i class="fixture-dot"></i>${a.name}</span><span class="fixture-score">${m.games[0]?m.games.map(g=>g[0]).join(' '):''}</span></div><div class="fixture-team"><span class="name"><i class="fixture-dot"></i>${b.name}</span><span class="fixture-score">${m.games[0]?m.games.map(g=>g[1]).join(' '):''}</span></div></div><div class="fixture-action">${(m.status==='live'||m.status==='upcoming')?`<button class="score-edit" data-match-id="${m.id}">${allowed?'Edit score':'Update score'}</button>`:`<span class="match-status">${scoreString(m)}</span>`}</div></article>`;}).join('');
  $$('.score-edit').forEach(b=>b.addEventListener('click',()=>openScore(b.dataset.matchId)));
}
function renderRotationFixtures(){
  $('#fixtureFormatNote').textContent='1 game · 21 points'; const matches=rotationMatches(); $('#fixturesList').innerHTML=matches.map(match=>`<article class="fixture-item ${match.status}" data-status="${match.status}" ${activeFilter!=='all'&&match.status!==activeFilter?'hidden':''}><div class="fixture-meta"><b>${match.status==='complete'?'PLAYED':`ROUND ${match.round}`}</b>${match.group}<br>Rotation ${match.slot}</div><div class="fixture-teams"><div class="fixture-team"><span class="name"><i class="fixture-dot"></i>${rotationPair(match.a)}</span><span class="fixture-score">${match.games[0]?match.games.map(game=>game[0]).join(' '):''}</span></div><div class="fixture-team"><span class="name"><i class="fixture-dot"></i>${rotationPair(match.b)}</span><span class="fixture-score">${match.games[0]?match.games.map(game=>game[1]).join(' '):''}</span></div></div><div class="fixture-action">${match.status==='complete'?`<span class="match-status">${scoreString(match)}</span>`:`<button class="score-edit" data-match-id="${match.id}">${canEdit()?'Edit score':'Update score'}</button>`}</div></article>`).join('')+`${data.rotation.rounds.length<3?`<div class="rotation-wait">Round ${data.rotation.rounds.length+1} groups appear after every group has finished the current round.</div>`:''}`; $$('.score-edit').forEach(button=>button.onclick=()=>openScore(button.dataset.matchId));
}
function renderRotationStandings(){
  $('#standingsTitle').textContent='Overall leaderboard'; $('#poolToggle').innerHTML=`<span class="rotation-round-badge">${data.rotation.rounds.length}/3 rounds</span>`; const rows=rotationOverallScores(); $('#standings').innerHTML=`<table class="standings-table rotation-table"><thead><tr><th>#</th><th>PLAYER</th><th>P</th><th>W</th><th>PTS</th></tr></thead><tbody>${rows.map((row,index)=>`<tr class="${index<3?'leader-row':''}"><td class="standing-rank">${index+1}</td><td>${row.player.name}</td><td>${row.played}</td><td>${row.wins}</td><td>${row.score}</td></tr>`).join('')}</tbody></table>`; $('.standings-note').textContent='Final places are decided by total points across all three rounds.'; }
function renderStandings(){ if(isRotation()){ renderRotationStandings(); return; } $('#standingsTitle').textContent='Pool standings'; $('#poolToggle').innerHTML='<button class="pool-toggle-btn active" data-pool="A">A</button><button class="pool-toggle-btn" data-pool="B">B</button>'; $$('.pool-toggle-btn').forEach(b=>b.onclick=()=>{activePool=b.dataset.pool;$$('.pool-toggle-btn').forEach(x=>x.classList.toggle('active',x===b));renderStandings();}); const rows=standings(activePool); $('#standings').innerHTML=`<table class="standings-table"><thead><tr><th>#</th><th>PAIR</th><th>P</th><th>W</th><th>+/-</th></tr></thead><tbody>${rows.map((r,i)=>`<tr><td class="standing-rank">${i+1}</td><td>${r.team.name}</td><td>${r.played}</td><td>${r.wins}</td><td>${r.for-r.against>0?'+':''}${r.for-r.against}</td></tr>`).join('')}</tbody></table>`; }
function seedName(pool,rank){return standings(pool)[rank-1]?.team || null}
function roundRow(t, winner=false){return `<div class="bracket-row ${winner?'winner':''} ${!t?'placeholder':''}"><span>${t?t.name:'TBD'}</span><b>${winner?'✓':''}</b></div>`}
function renderBracket(){ if(isRotation()){ renderRotationProgress(); return; } $('.bracket-section .eyebrow').innerHTML='<span></span> The business end'; $('.bracket-section h2').textContent='Knockout bracket'; $('.bracket-key').innerHTML='<span><i class="key-win"></i> Advances</span><span><i></i> To be played</span>'; $('.round-labels').innerHTML='<span>Quarterfinals</span><span>Semifinals</span><span>Final</span>'; const a=standings('A'),b=standings('B'); const qs=[['QF 1',a[0].team,b[3].team],['QF 2',b[1].team,a[2].team],['QF 3',b[0].team,a[3].team],['QF 4',a[1].team,b[2].team]]; $('#bracketGrid').className='bracket-grid'; $('#bracketGrid').innerHTML=`<div class="bracket-col">${qs.map(q=>`<div class="bracket-match"><div class="bracket-row placeholder"><span>${q[0]}</span><b>—</b></div>${roundRow(q[1])}${roundRow(q[2])}</div>`).join('')}</div><div class="bracket-col semi"><div class="bracket-match"><div class="bracket-row placeholder"><span>SF 1</span><b>—</b></div>${roundRow(null)}${roundRow(null)}</div><div class="bracket-match"><div class="bracket-row placeholder"><span>SF 2</span><b>—</b></div>${roundRow(null)}${roundRow(null)}</div></div><div class="bracket-col final"><div class="bracket-match final-card"><div class="bracket-row placeholder"><span>FINAL · 15:15</span><b>🏆</b></div>${roundRow(null)}${roundRow(null)}</div></div>`; }
function renderRotationProgress(){
  $('.bracket-section .eyebrow').innerHTML='<span></span> Rotation League'; $('.bracket-section h2').textContent='Three rounds. One leaderboard.'; $('.bracket-key').innerHTML='<span><i class="key-win"></i> Total points decide the winners</span>'; $('.round-labels').innerHTML='<span>Round 1</span><span>Round 2</span><span>Round 3</span>'; const rounds=data.rotation.rounds; $('#bracketGrid').className='bracket-grid rotation-progress'; $('#bracketGrid').innerHTML=[1,2,3].map(number=>{ const round=rounds[number-1]; if(!round)return `<div class="rotation-round-card pending-round"><p>ROUND ${number}</p><h3>Waiting for round ${number-1}</h3><span>Players regroup by their current group place.</span></div>`; return `<div class="rotation-round-card"><p>ROUND ${number}</p><h3>${number===1?'Random groups':number===2?'Place groups':'Final regroup'}</h3>${round.groups.map(group=>`<div class="rotation-group"><b>${group.name}</b>${rotationRoundScores(round,group).map((row,index)=>`<span>${number>1?`${index+1}. `:''}${row.player.name}</span>`).join('')}</div>`).join('')}</div>`; }).join('');
}
function renderRole(){ const pill=$('#rolePill'); const admin=data.role==='admin'; pill.className=`role-pill ${admin?'admin':'visitor'}`; pill.innerHTML=`<span></span> ${admin?'Organiser':'Viewer'}`; $('#adminButton').textContent=admin?'Control room':'Admin access'; }
function renderRequests(){ const pending=data.requests.filter(r=>r.status==='pending'); $('#requestBadge').textContent=pending.length; $('#requestsPanel').innerHTML=pending.length?pending.map(r=>`<div class="request-row"><div class="request-person"><span class="request-initials">${initials(r.name)}</span><div><strong>${r.name}</strong><span>${r.team||'No pair selected'} · requested score access</span></div></div><div class="request-buttons"><button class="small-button" data-deny="${r.id}">Decline</button><button class="small-button approve" data-approve="${r.id}">Approve</button></div></div>`).join(''):`<p class="empty-requests">No scorekeeper requests waiting for you.</p>`; $$('[data-approve]').forEach(b=>b.onclick=()=>{const r=data.requests.find(x=>x.id===b.dataset.approve);r.status='approved';data.approved.push(r.name.toLowerCase());save();renderAll();toast(`${r.name} can now record scores.`)}); $$('[data-deny]').forEach(b=>b.onclick=()=>{data.requests.find(x=>x.id===b.dataset.deny).status='declined';save();renderRequests();}); }
function canEdit(){return data.role==='admin'||(data.scorerName&&data.approved.includes(data.scorerName.toLowerCase()))}
function renderTeamsSelect(){ const choices=isRotation()?data.players.map(person=>person.name):data.teams.map(t=>t.name); $('#requestTeam').innerHTML='<option value="">Choose '+(isRotation()?'your name':'a pair')+'</option>'+choices.map(choice=>`<option>${choice}</option>`).join(''); }
function renderTournamentMeta(){ $('#eventName').textContent=data.tournament.name; $('#eventDate').textContent=data.tournament.date; $('#eventVenue').textContent=data.tournament.venue; $('#heroDescription').textContent=isRotation()?'Sixteen players rotate partners in equal groups, building a personal points total over three rounds.':'Eight pairs. One good Saturday. Follow the pool stage, celebrate every rally, and see who takes the court in the final.'; }
function renderRules(){ if(isRotation()){$('#formatRuleTitle').textContent='Rotate, rank, regroup';$('#formatRuleText').textContent='Players are randomly grouped for doubles round robins. After each round, equal placing players regroup; the final top 3 are decided by total points from every match.';}else{$('#formatRuleTitle').textContent='Play your pool';$('#formatRuleText').textContent='Fixed doubles pairs play a round robin in their pool before the knockout rounds begin.';} }
function renderAll(){renderTournamentMeta();renderNext();renderStats();renderFixtures();renderStandings();renderBracket();renderRole();renderRules();renderRequests();}
function toast(message){const el=$('#toast');el.textContent=message;el.classList.add('show');setTimeout(()=>el.classList.remove('show'),3500)}
function playerInitials(name){ return name.trim().split(/\s+/).map(word=>word[0]||'').join('').slice(0,2).toUpperCase() || 'DB'; }
function displayDate(value){ const date=new Date(`${value}T12:00:00`); return Number.isNaN(date.valueOf())?'Tournament day':`${date.toLocaleDateString(undefined,{weekday:'long',day:'numeric',month:'long'})} · 09:00`; }
function generatedMatches(){
  const rounds=[[[0,1],[2,3]],[[0,2],[1,3]],[[0,3],[1,2]]], matches=[]; const times=['09:00','10:15','11:30'];
  rounds.forEach((round,roundIndex)=>['A','B'].forEach((pool,poolIndex)=>round.forEach((pair,matchIndex)=>{ const offset=pool==='A'?0:4; const court=pool==='A'?matchIndex+1:matchIndex+3; matches.push({id:`m${matches.length+1}`,pool,court:`Court ${court}`,time:times[roundIndex],a:`t${offset+pair[0]+1}`,b:`t${offset+pair[1]+1}`,status:'upcoming',games:[]}); }))); return matches;
}
function renderPairInputs(format=$('#newFormat')?.value||'teams'){
  const rotation=format==='rotation'; $('#playerBuilderTitle').textContent=rotation?'Your rotation players':'Your doubles pairs'; $('#playerCountLabel').textContent='16 players'; $('#newTournamentIntro').textContent=rotation?'Add 16 individual players. The app randomly places them into four equal groups, rotates doubles partners, and carries player points through three rounds.':'Add eight pairs (16 players). Pairs 1–4 start in Pool A and pairs 5–8 in Pool B. Fixtures and the knockout draw are generated automatically.'; $('#formatBuilderHelp').textContent=rotation?'All 16 players are shuffled into four equal groups of four. Partners rotate in each group, and each player keeps their own points total.':'Enter eight fixed pairs. Pairs 1–4 start in Pool A and pairs 5–8 in Pool B.';
  $('#playerPairs').classList.toggle('rotation-player-grid',rotation); $('#playerPairs').innerHTML=rotation?Array.from({length:16},(_,index)=>`<label class="rotation-player-input"><span>PLAYER ${String(index+1).padStart(2,'0')}</span><input data-rotation-player="${index}" type="text" maxlength="30" placeholder="Player name" required /></label>`).join(''):Array.from({length:8},(_,index)=>`<div class="pair-input-row"><div class="pair-number"><b>${String(index+1).padStart(2,'0')}</b><span>Pool ${index<4?'A':'B'}</span></div><label>Player 1<input data-player="${index}-a" type="text" maxlength="30" placeholder="First player" required /></label><label>Player 2<input data-player="${index}-b" type="text" maxlength="30" placeholder="Second player" required /></label></div>`).join('');
}
function openNewTournament(){
  $('#newFormat').value='teams'; renderPairInputs('teams'); $('#newEventName').value=''; $('#newEventVenue').value=''; $('#newEventDate').value=new Date().toISOString().slice(0,10); $('#newTournamentMessage').textContent=''; $('#dashboardDialog').close(); $('#newTournamentDialog').showModal();
}
function openScore(id){ const m=isRotation()?rotationMatchDetails(id):data.matches.find(match=>match.id===id); if(!canEdit()){editingMatchId=id; $('#accessMessage').textContent=''; $('#accessDialog').showModal(); return;} editingMatchId=id; $('#scoreMatchTitle').textContent=isRotation()?`${rotationPair(m.a)} vs ${rotationPair(m.b)}`:`${team(m.a).name} vs ${team(m.b).name}`; $('#scoreTeams').textContent=isRotation()?`Round ${m.round} · ${m.group} · Rotation ${m.slot}`:`${m.court} · Pool ${m.pool} · ${m.time}`; $('#scoreFormatHint').textContent='Record one game to 21 points. The higher score wins the match.'; $('#game2Field').classList.add('hidden'); $('#game3Field').classList.add('hidden'); const fields=$$('#scoreForm input[type=number]'); fields.forEach((f,i)=>f.value=m.games[Math.floor(i/2)]?.[i%2]??''); $('#scoreMessage').textContent=''; $('#scoreDialog').showModal(); }
$('#requestAccessButton').onclick=()=>{$('#accessMessage').textContent='';$('#accessDialog').showModal();};
$('#accessForm').addEventListener('submit',e=>{e.preventDefault();const name=$('#requestName').value.trim();if(!name)return;data.scorerName=name;const previous=data.requests.find(r=>r.name.toLowerCase()===name.toLowerCase());if(data.approved.includes(name.toLowerCase())){$('#accessDialog').close();toast('You already have approval — you can update scores.');renderAll();return;}if(previous){$('#accessMessage').textContent='Your request is already waiting for approval.';return;}data.requests.push({id:Date.now().toString(),name,team:$('#requestTeam').value,status:'pending'});save();$('#accessMessage').textContent='Request sent. Ask the organiser to approve it.';renderRequests();});
$('#adminButton').onclick=()=>{if(data.role==='admin'){$('#dashboardDialog').showModal();return;}$('#adminPasscode').value='';$('#adminMessage').textContent='';$('#adminDialog').showModal();};
$('#adminForm').addEventListener('submit',e=>{e.preventDefault();if($('#adminPasscode').value==='rallyadmin'){data.role='admin';save();$('#adminDialog').close();renderAll();$('#dashboardDialog').showModal();toast('Organiser dashboard unlocked.');}else $('#adminMessage').textContent='That passcode is not right. Try again.';});
$('#dashboardClose').onclick=()=>$('#dashboardDialog').close(); $('#logOutButton').onclick=()=>{data.role='visitor';save();$('#dashboardDialog').close();renderAll();toast('Signed out of organiser mode.');};
$$('.dash-tab').forEach(b=>b.onclick=()=>{$$('.dash-tab').forEach(x=>x.classList.toggle('active',x===b));$('#requestsPanel').classList.toggle('hidden',b.dataset.dash!=='requests');$('#settingsPanel').classList.toggle('hidden',b.dataset.dash!=='settings');});
$('#resetButton').onclick=()=>{if(confirm('Reset all score and access-request data to the demo state?')){data=structuredClone(DEFAULT_DATA);save();$('#dashboardDialog').close();renderAll();toast('Demo tournament reset.')}};
$('#newTournamentButton').onclick=openNewTournament;
$('#newTournamentCancel').onclick=()=>$('#newTournamentDialog').close();
$('#newFormat').onchange=()=>renderPairInputs($('#newFormat').value);
$('#newTournamentForm').addEventListener('submit',e=>{
  e.preventDefault(); const name=$('#newEventName').value.trim(), venue=$('#newEventVenue').value.trim(), date=$('#newEventDate').value, format=$('#newFormat').value;
  if(!name||!venue||!date){$('#newTournamentMessage').textContent='Please add the tournament name, date, and venue.';return;}
  const role=data.role;
  if(format==='rotation'){
    const names=$$('[data-rotation-player]').map(input=>input.value.trim()); if(names.some(value=>!value)){ $('#newTournamentMessage').textContent='Please enter all 16 player names.';return; } if(new Set(names.map(value=>value.toLowerCase())).size!==names.length){$('#newTournamentMessage').textContent='Each player name must be unique.';return;}
    if(!confirm(`Create “${name}”? This will replace the current tournament, results, and scorekeeper approvals.`)) return;
    const rotationPlayers=names.map((person,index)=>({id:`p${index+1}`,name:person})), randomized=shuffle(rotationPlayers.map(person=>person.id)), equalGroups=Array.from({length:4},(_,index)=>randomized.slice(index*4,index*4+4)); data={tournament:{name,venue,date:displayDate(date),format:'rotation'},teams:[],matches:[],players:rotationPlayers,rotation:{rounds:[buildRotationRound(1,equalGroups)]},requests:[],approved:[],role,scorerName:''};
  } else {
    const pairInputs=$$('#playerPairs input'),pairs=[]; for(let i=0;i<pairInputs.length;i+=2){const first=pairInputs[i].value.trim(),second=pairInputs[i+1].value.trim();if(!first||!second){$('#newTournamentMessage').textContent='Please enter both players for every pair.';return;}pairs.push([first,second]);}
    if(!confirm(`Create “${name}”? This will replace the current tournament, results, and scorekeeper approvals.`)) return;
    data={tournament:{name,venue,date:displayDate(date),format:'teams'},teams:pairs.map(([first,second],index)=>({id:`t${index+1}`,name:`${first} & ${second}`,short:`${playerInitials(first)}${playerInitials(second)}`.slice(0,4),players:`${first} · ${second}`,pool:index<4?'A':'B'})),matches:generatedMatches(),players:[],rotation:null,requests:[],approved:[],role,scorerName:''};
  }
  activePool='A';activeFilter='all';save();$('#newTournamentDialog').close();renderTeamsSelect();renderAll();window.scrollTo({top:0,behavior:'smooth'});toast(`${name} is ready to play.`);
});
$('#scoreForm').addEventListener('submit',e=>{e.preventDefault();const m=isRotation()?rotationMatchById(editingMatchId):data.matches.find(match=>match.id===editingMatchId);const vals=$$('#scoreForm input[type=number]').map(f=>f.value===''?null:Number(f.value));const games=[];for(let i=0;i<3;i++){if(vals[i*2]!==null&&vals[i*2+1]!==null)games.push([vals[i*2],vals[i*2+1]]);}if(games.length<1){$('#scoreMessage').textContent='Please record the game score.';return;}const aGames=games.filter(([a,b])=>a>b).length,bGames=games.filter(([a,b])=>b>a).length;if(aGames===bGames){$('#scoreMessage').textContent='The result needs a winning pair.';return;}m.games=[games[0]];m.status='complete';const nextRound=isRotation()?advanceRotation():null;save();$('#scoreDialog').close();renderAll();toast(nextRound?`Round ${nextRound.number} groups are ready.`:'Match result saved — standings updated.');});
$$('.pool-toggle-btn').forEach(b=>b.onclick=()=>{activePool=b.dataset.pool;$$('.pool-toggle-btn').forEach(x=>x.classList.toggle('active',x===b));renderStandings();});
$$('.filter-tab').forEach(b=>b.onclick=()=>{activeFilter=b.dataset.filter;$$('.filter-tab').forEach(x=>x.classList.toggle('active',x===b));renderFixtures();});
$$('[data-view]').forEach(b=>b.onclick=()=>{const target=$('#'+b.dataset.view);target.scrollIntoView({behavior:'smooth',block:'start'});$$('[data-view]').forEach(x=>x.classList.toggle('active',x===b));});
$$('[data-scroll]').forEach(b=>b.onclick=()=>$('#'+b.dataset.scroll).scrollIntoView({behavior:'smooth',block:'start'}));
$$('[data-view-target]').forEach(b=>b.onclick=()=>$('#'+b.dataset.viewTarget).scrollIntoView({behavior:'smooth',block:'start'}));
setInterval(()=>{$('#clock').textContent=new Date().toLocaleTimeString([],{hour:'2-digit',minute:'2-digit'});},1000);
renderTeamsSelect();renderAll();
