const DEFAULT_DATA = {
  teams: [
    { id: 't1', name: 'Maya & Nia', short: 'MN', players: 'Maya Chen · Nia Kapoor', pool: 'A' },
    { id: 't2', name: 'Leo & Tomas', short: 'LT', players: 'Leo Martin · Tomas Reed', pool: 'A' },
    { id: 't3', name: 'Aisha & Bea', short: 'AB', players: 'Aisha Khan · Bea Olsen', pool: 'A' },
    { id: 't4', name: 'Owen & Kai', short: 'OK', players: 'Owen Wells · Kai Tan', pool: 'A' },
    { id: 't5', name: 'Zoe & Isla', short: 'ZI', players: 'Zoe Park · Isla Moore', pool: 'B' },
    { id: 't6', name: 'Finn & Arun', short: 'FA', players: 'Finn Cole · Arun Mehta', pool: 'B' },
    { id: 't7', name: 'Cleo & Sam', short: 'CS', players: 'Cleo James · Sam Hall', pool: 'B' },
    { id: 't8', name: 'Noah & Jules', short: 'NJ', players: 'Noah Grant · Jules Perry', pool: 'B' }
  ],
  matches: [
    { id: 'm1', pool: 'A', court: 'Court 1', time: '09:00', a: 't1', b: 't2', status: 'complete', games: [[21, 16]] },
    { id: 'm2', pool: 'A', court: 'Court 2', time: '09:00', a: 't3', b: 't4', status: 'complete', games: [[18, 21]] },
    { id: 'm3', pool: 'B', court: 'Court 3', time: '09:00', a: 't5', b: 't6', status: 'complete', games: [[21, 12]] },
    { id: 'm4', pool: 'B', court: 'Court 4', time: '09:00', a: 't7', b: 't8', status: 'complete', games: [[21, 17]] },
    { id: 'm5', pool: 'A', court: 'Court 2', time: '10:15', a: 't1', b: 't3', status: 'live', games: [] },
    { id: 'm6', pool: 'A', court: 'Court 1', time: '10:15', a: 't2', b: 't4', status: 'upcoming', games: [] },
    { id: 'm7', pool: 'B', court: 'Court 4', time: '10:15', a: 't5', b: 't7', status: 'live', games: [] },
    { id: 'm8', pool: 'B', court: 'Court 3', time: '10:15', a: 't6', b: 't8', status: 'upcoming', games: [] },
    { id: 'm9', pool: 'A', court: 'Court 1', time: '11:30', a: 't1', b: 't4', status: 'upcoming', games: [] },
    { id: 'm10', pool: 'A', court: 'Court 2', time: '11:30', a: 't2', b: 't3', status: 'upcoming', games: [] },
    { id: 'm11', pool: 'B', court: 'Court 3', time: '11:30', a: 't5', b: 't8', status: 'upcoming', games: [] },
    { id: 'm12', pool: 'B', court: 'Court 4', time: '11:30', a: 't6', b: 't7', status: 'upcoming', games: [] }
  ],
  tournament: { name: 'Friendly doubles,', date: 'Saturday, 21 September · 09:00', venue: 'Rally Club Courts', format: 'teams' },
  players: [], rotation: null, requests: [], approved: [], role: 'visitor', scorerName: ''
};
let data = loadData();
let activePool = 'A'; let activeFilter = 'all'; let editingMatchId = null;
const $ = (s) => document.querySelector(s);
const $$ = (s) => [...document.querySelectorAll(s)];
function loadData(){ try { const saved=JSON.parse(localStorage.getItem('rally-club-tournament')); return saved?{...structuredClone(DEFAULT_DATA),...saved,tournament:{...DEFAULT_DATA.tournament,...saved.tournament}}:structuredClone(DEFAULT_DATA); } catch { return structuredClone(DEFAULT_DATA); } }
function save(){ localStorage.setItem('rally-club-tournament', JSON.stringify(data)); }
function team(id){ return data.teams.find(t => t.id === id); }
function initials(name){ return name.split(' ').map(p => p[0]).join('').slice(0,2).toUpperCase(); }
function isRotation(){ return data.tournament.format==='rotation'; }
function player(id){ return data.players.find(p=>p.id===id); }
function rotationMatches(){ return data.rotation?.rounds.flatMap(round=>round.groups.flatMap(group=>group.matches.map(match=>({...match,round:round.number,group:group.name}))))||[]; }
function rotationMatchById(id){ return data.rotation?.rounds.flatMap(round=>round.groups.flatMap(group=>group.matches)).find(match=>match.id===id); }
function rotationMatchDetails(id){ return rotationMatches().find(match=>match.id===id); }
function rotationPair(ids){ return ids.map(id=>player(id)?.name||'TBD').join(' & '); }
function shuffle(items){ return [...items].sort(()=>Math.random()-.5); }
const EXPERIENCE_SCORE={beginner:1,intermediate:2,advanced:3,competitive:4};
function experienceScore(player){ return EXPERIENCE_SCORE[player.experience]||EXPERIENCE_SCORE.intermediate; }
function rotationGroupSizes(playerCount){ let groupCount=Math.ceil(playerCount/5); while(groupCount>1&&Math.floor(playerCount/groupCount)<4)groupCount--; const base=Math.floor(playerCount/groupCount), extras=playerCount%groupCount; return Array.from({length:groupCount},(_,index)=>base+(index>=groupCount-extras?1:0)); }
function balancedRotationGroups(players,groupSizes){ const groups=groupSizes.map(()=>[]), slots=[]; for(let layer=0;layer<Math.max(...groupSizes);layer++){ const eligible=groupSizes.map((size,index)=>size>layer?index:null).filter(index=>index!==null); slots.push(...(layer%2?eligible.reverse():eligible)); } const ranked=shuffle(players).sort((a,b)=>experienceScore(b)-experienceScore(a)); ranked.forEach((person,index)=>groups[slots[index]].push(person.id)); return groups; }
function buildRotationGroupMatches(ids,roundNumber,groupIndex){
  const pairings=[[[0,1],[2,3]],[[0,2],[1,3]],[[0,3],[1,2]]], matches=[], matchCount=Math.ceil(ids.length*3/4), extraAppearances=matchCount*4-ids.length*3, targets=Object.fromEntries(ids.map(id=>[id,3])), played=Object.fromEntries(ids.map(id=>[id,0])); for(let index=0;index<extraAppearances;index++)targets[ids[(roundNumber+groupIndex+index)%ids.length]]++;
  for(let matchIndex=0;matchIndex<matchCount;matchIndex++){ const players=[...ids].filter(id=>played[id]<targets[id]).sort((a,b)=>(targets[b]-played[b])-(targets[a]-played[a])||played[a]-played[b]||ids.indexOf(a)-ids.indexOf(b)).slice(0,4); players.forEach(id=>played[id]++); const pairs=pairings[matchIndex%pairings.length]; matches.push({id:`r${roundNumber}g${groupIndex+1}m${matches.length+1}`,a:pairs[0].map(index=>players[index]),b:pairs[1].map(index=>players[index]),status:'upcoming',games:[],slot:matches.length+1}); } return matches;
}
function poolLabel(index){ let label='',number=index+1; while(number>0){const remainder=(number-1)%26;label=String.fromCharCode(65+remainder)+label;number=Math.floor((number-1)/26);} return label; }
function buildRotationRound(number,groups){ const placement=['1st-place group','2nd-place group','3rd-place group','4th-place group']; const exactPlaceGroups=groups.length===groups[0]?.length; return {number,groups:groups.map((ids,index)=>({id:`r${number}g${index+1}`,name:number===1?`Group ${poolLabel(index)}`:(exactPlaceGroups&&index<4?placement[index]:`Seeded group ${index+1}`),playerIds:ids,matches:buildRotationGroupMatches(ids,number,index)}))}; }
function rotationRoundScores(round,group){
  const scores=group.playerIds.map(id=>({player:player(id),score:0,wins:0,played:0}));
  group.matches.filter(match=>match.status==='complete').forEach(match=>{ const aScore=scores.filter(row=>match.a.includes(row.player.id)), bScore=scores.filter(row=>match.b.includes(row.player.id)); const aGames=match.games.filter(([a,b])=>a>b).length,bGames=match.games.filter(([a,b])=>b>a).length; const aPoints=match.games.reduce((sum,[a])=>sum+a,0),bPoints=match.games.reduce((sum,[,b])=>sum+b,0); aScore.forEach(row=>{row.played++;row.score+=aPoints;if(aGames>bGames)row.wins++;});bScore.forEach(row=>{row.played++;row.score+=bPoints;if(bGames>aGames)row.wins++;}); });
  return scores.sort((a,b)=>b.score-a.score||b.wins-a.wins||a.player.name.localeCompare(b.player.name));
}
function rotationOverallScores(){ const scores=data.players.map(person=>({player:person,score:0,wins:0,played:0})); rotationMatches().filter(match=>match.status==='complete').forEach(match=>{ const aRows=scores.filter(row=>match.a.includes(row.player.id)),bRows=scores.filter(row=>match.b.includes(row.player.id)); const aGames=match.games.filter(([a,b])=>a>b).length,bGames=match.games.filter(([a,b])=>b>a).length,aPoints=match.games.reduce((sum,[a])=>sum+a,0),bPoints=match.games.reduce((sum,[,b])=>sum+b,0); aRows.forEach(row=>{row.played++;row.score+=aPoints;if(aGames>bGames)row.wins++;});bRows.forEach(row=>{row.played++;row.score+=bPoints;if(bGames>aGames)row.wins++;}); }); return scores.sort((a,b)=>b.score-a.score||b.wins-a.wins||a.player.name.localeCompare(b.player.name)); }
function rotationRoundComplete(round){ return round.groups.every(group=>group.matches.every(match=>match.status==='complete')); }
function regroupRotation(groups){ const groupSizes=data.rotation.groupSizes||groups.map(group=>group.playerIds.length), ranked=groups.map(group=>rotationRoundScores({groups:[group]},group).map(row=>row.player.id)), maxSize=Math.max(...groupSizes), byPlace=Array.from({length:maxSize},(_,place)=>ranked.map(group=>group[place]).filter(Boolean)).flat(); let offset=0; return groupSizes.map(size=>{const group=byPlace.slice(offset,offset+size);offset+=size;return group;}); }
function advanceRotation(){ const rounds=data.rotation.rounds; const current=rounds[rounds.length-1]; if(!rotationRoundComplete(current)||rounds.length>=3)return null; const next=buildRotationRound(rounds.length+1,regroupRotation(current.groups)); rounds.push(next); return next; }
function teamBlock(t, reverse=false){ return `<div class="team-block ${reverse?'reverse':''}"><span class="team-avatar">${t.short}</span><div class="team-names">${t.name}<small>${t.players}</small></div></div>`; }
function matchWinner(match){ if(!match.games?.length) return null; let a=0,b=0; match.games.forEach(([x,y]) => x>y ? a++ : y>x ? b++ : null); return a===b ? null : a>b ? match.a : match.b; }
function scoreString(match){ return match.games?.map(([a,b])=>`${a}–${b}`).join('  ') || '—'; }
function standings(pool){
  const rows = data.teams.filter(t=>t.pool===pool).map(t=>({team:t,played:0,wins:0,losses:0,for:0,against:0}));
  data.matches.filter(m=>m.pool===pool && m.status==='complete').forEach(m=>{ const ra=rows.find(r=>r.team.id===m.a), rb=rows.find(r=>r.team.id===m.b); const win=matchWinner(m); ra.played++;rb.played++; if(win===m.a){ra.wins++;rb.losses++;}else if(win===m.b){rb.wins++;ra.losses++;} m.games.forEach(([a,b])=>{ra.for+=a;ra.against+=b;rb.for+=b;rb.against+=a;}); });
  return rows.sort((x,y)=>y.wins-x.wins || (y.for-y.against)-(x.for-x.against) || y.for-x.for);
}
function renderNext(){
  if(isRotation()){ const m=rotationMatches().find(match=>match.status==='upcoming'); if(!m){$('#nextMatch').innerHTML='<p class="rotation-ready">All three rounds are complete. See the leaderboard below.</p>';return;} $('#nextMatch').innerHTML=`<div class="next-match rotation-next"><div class="rotation-pair"><span>${rotationPair(m.a)}</span><small>Round ${m.round} · ${m.group}</small></div><div class="versus">VS<br><small>GROUP GAME ${m.slot}</small></div><div class="rotation-pair reverse"><span>${rotationPair(m.b)}</span><small>Round ${m.round} · ${m.group}</small></div></div>`; return; }
  const m = data.matches.find(m=>m.status==='live') || data.matches.find(m=>m.status==='upcoming'); if(!m) return; $('#nextMatch').innerHTML=`<div class="next-match">${teamBlock(team(m.a))}<div class="versus">VS<br><small>POOL ${m.pool}</small></div>${teamBlock(team(m.b),true)}</div>`;
}
function renderStats(){ const matches=isRotation()?rotationMatches():data.matches, done=matches.filter(m=>m.status==='complete').length, left=Math.max(0,matches.length-done); $('#playedCount').textContent=done; $('#remainingCount').textContent=left; $('#liveStatus').textContent=isRotation()?`Round ${data.rotation.rounds.length} of 3`:`${matches.filter(m=>m.status==='live').length} courts live`; const rotationGroupSizes=data.rotation?.groupSizes||data.rotation?.rounds[0]?.groups.map(group=>group.playerIds.length)||[4], groupLabel=[...new Set(rotationGroupSizes)].join('–'); $('#formatStatNumber').textContent=isRotation()?data.rotation.rounds[0].groups.length:poolIds().length; $('#formatStatLabel').textContent=isRotation()?`${data.players.length} players · groups of ${groupLabel}`:`${data.teams.length} pairs · ${poolIds().length} league ${poolIds().length===1?'group':'groups'}`; }
function renderFixtures(){
  if(isRotation()){ renderRotationFixtures(); return; }
  $('#fixtureFormatNote').textContent='1 game · 21 points'; $('#fixturesEyebrow').innerHTML='<span></span> League stage'; $('#fixturesTitle').textContent='League fixtures';
  const statusCopy={live:'LIVE NOW',upcoming:'UP NEXT',complete:'PLAYED'};
  $('#fixturesList').innerHTML=data.matches.map(m=>{const a=team(m.a),b=team(m.b),allowed=canEdit(); return `<article class="fixture-item ${m.status}" data-status="${m.status}" ${activeFilter!=='all'&&m.status!==activeFilter?'hidden':''}><div class="fixture-meta"><b>${statusCopy[m.status]}</b>${m.time}<br>${m.court}</div><div class="fixture-teams"><div class="fixture-team"><span class="name"><i class="fixture-dot"></i>${a.name}</span><span class="fixture-score">${m.games[0]?m.games.map(g=>g[0]).join(' '):''}</span></div><div class="fixture-team"><span class="name"><i class="fixture-dot"></i>${b.name}</span><span class="fixture-score">${m.games[0]?m.games.map(g=>g[1]).join(' '):''}</span></div></div><div class="fixture-action">${(m.status==='live'||m.status==='upcoming')?`<button class="score-edit" data-match-id="${m.id}">${allowed?'Edit score':'Update score'}</button>`:`<span class="match-status">${scoreString(m)}</span>`}</div></article>`;}).join('');
  $$('.score-edit').forEach(b=>b.addEventListener('click',()=>openScore(b.dataset.matchId)));
}
function renderRotationFixtures(){
  $('#fixtureFormatNote').textContent='1 game · 21 points'; $('#fixturesEyebrow').innerHTML='<span></span> Rotation League'; $('#fixturesTitle').textContent='Rotation fixtures'; const matches=rotationMatches(); $('#fixturesList').innerHTML=matches.map(match=>`<article class="fixture-item ${match.status}" data-status="${match.status}" ${activeFilter!=='all'&&match.status!==activeFilter?'hidden':''}><div class="fixture-meta"><b>${match.status==='complete'?'PLAYED':`ROUND ${match.round}`}</b>${match.group}<br>Group game ${match.slot}</div><div class="fixture-teams"><div class="fixture-team"><span class="name"><i class="fixture-dot"></i>${rotationPair(match.a)}</span><span class="fixture-score">${match.games[0]?match.games.map(game=>game[0]).join(' '):''}</span></div><div class="fixture-team"><span class="name"><i class="fixture-dot"></i>${rotationPair(match.b)}</span><span class="fixture-score">${match.games[0]?match.games.map(game=>game[1]).join(' '):''}</span></div></div><div class="fixture-action">${match.status==='complete'?`<span class="match-status">${scoreString(match)}</span>`:`<button class="score-edit" data-match-id="${match.id}">${canEdit()?'Edit score':'Update score'}</button>`}</div></article>`).join('')+`${data.rotation.rounds.length<3?`<div class="rotation-wait">Round ${data.rotation.rounds.length+1} groups appear after every group has finished the current round.</div>`:''}`; $$('.score-edit').forEach(button=>button.onclick=()=>openScore(button.dataset.matchId));
}
function renderRotationStandings(){
  $('#standingsTitle').textContent='Overall leaderboard'; $('#poolToggle').innerHTML=`<span class="rotation-round-badge">${data.rotation.rounds.length}/3 rounds</span>`; const rows=rotationOverallScores(); $('#standings').innerHTML=`<table class="standings-table rotation-table"><thead><tr><th>#</th><th>PLAYER</th><th>P</th><th>W</th><th>PTS</th></tr></thead><tbody>${rows.map((row,index)=>`<tr class="${index<3?'leader-row':''}"><td class="standing-rank">${index+1}</td><td>${row.player.name}</td><td>${row.played}</td><td>${row.wins}</td><td>${row.score}</td></tr>`).join('')}</tbody></table>`; $('.standings-note').textContent='Final places are decided by total points across all three rounds.'; }
function poolIds(){ return [...new Set(data.teams.map(t=>t.pool))]; }
function renderStandings(){ if(isRotation()){ renderRotationStandings(); return; } const pools=poolIds(); if(!pools.includes(activePool)) activePool=pools[0]; $('#standingsTitle').textContent=pools.length===1?'League standings':'Pool standings'; $('#poolToggle').innerHTML=pools.map(pool=>`<button class="pool-toggle-btn ${pool===activePool?'active':''}" data-pool="${pool}">${pool}</button>`).join(''); $$('.pool-toggle-btn').forEach(b=>b.onclick=()=>{activePool=b.dataset.pool;renderStandings();}); const rows=standings(activePool); $('#standings').innerHTML=`<table class="standings-table"><thead><tr><th>#</th><th>PAIR</th><th>P</th><th>W</th><th>+/-</th></tr></thead><tbody>${rows.map((r,i)=>`<tr><td class="standing-rank">${i+1}</td><td>${r.team.name}</td><td>${r.played}</td><td>${r.wins}</td><td>${r.for-r.against>0?'+':''}${r.for-r.against}</td></tr>`).join('')}</tbody></table>`; $('.standings-note').textContent='Ranked by wins, then points difference.'; }
function overallTeamRankings(){ return poolIds().flatMap(pool=>standings(pool).map(row=>({...row,pool,rate:row.played?row.wins/row.played:0}))).sort((a,b)=>b.rate-a.rate||b.wins-a.wins||(b.for-b.against)-(a.for-a.against)||b.for-a.for); }
function roundRow(t, winner=false){ const name=typeof t==='string'?t:t?.name; return `<div class="bracket-row ${winner?'winner':''} ${!name?'placeholder':''}"><span>${name||'TBD'}</span><b>${winner?'✓':''}</b></div>`}
function bracketCard(label,a,b,final=false){ return `<div class="bracket-match ${final?'final-card':''}"><div class="bracket-row placeholder"><span>${label}</span><b>${final?'🏆':'—'}</b></div>${roundRow(a)}${roundRow(b)}</div>`; }
function renderBracket(){ if(isRotation()){ renderRotationProgress(); return; } const ranked=overallTeamRankings(), size=ranked.length>=8?8:ranked.length>=4?4:ranked.length>=2?2:0, seeds=ranked.slice(0,size).map(row=>row.team); $('.bracket-section .eyebrow').innerHTML='<span></span> The business end'; $('.bracket-section h2').textContent=size>=2?'Knockout bracket':'League standings'; $('.bracket-key').innerHTML=size>=2?`<span><i class="key-win"></i> Top ${size} qualify</span><span><i></i> Seeded by league results</span>`:'<span><i></i> Add at least two pairs to create a final</span>'; const labels=size>=8?['Quarterfinals','Semifinals','Final']:size>=4?['Semifinals','Final']:['Final']; $('.round-labels').className='round-labels dynamic-bracket-labels'; $('.round-labels').style.setProperty('--bracket-columns',labels.length); $('.round-labels').innerHTML=labels.map(label=>`<span>${label}</span>`).join(''); const columns=size>=8?[[['QF 1',seeds[0],seeds[7]],['QF 2',seeds[3],seeds[4]],['QF 3',seeds[1],seeds[6]],['QF 4',seeds[2],seeds[5]]],[['SF 1','Winner QF 1','Winner QF 2'],['SF 2','Winner QF 3','Winner QF 4']],[['FINAL · 15:15','Winner SF 1','Winner SF 2']]]:size>=4?[[['SF 1',seeds[0],seeds[3]],['SF 2',seeds[1],seeds[2]]],[['FINAL · 15:15','Winner SF 1','Winner SF 2']]]:size===2?[[['FINAL · 15:15',seeds[0],seeds[1]]]]:[]; $('#bracketGrid').className='bracket-grid dynamic-bracket-grid'; $('#bracketGrid').style.setProperty('--bracket-columns',columns.length||1); $('#bracketGrid').innerHTML=columns.map((column,index)=>`<div class="bracket-col ${index===columns.length-1?'final':''}">${column.map(match=>bracketCard(...match,index===columns.length-1)).join('')}</div>`).join('')||'<p class="rotation-ready">The league fixtures will appear after teams are added.</p>'; }
function renderRotationProgress(){
  $('.bracket-section .eyebrow').innerHTML='<span></span> Rotation League'; $('.bracket-section h2').textContent='Three rounds. One leaderboard.'; $('.bracket-key').innerHTML='<span><i class="key-win"></i> Total points decide the winners</span>'; $('.round-labels').className='round-labels'; $('.round-labels').style.removeProperty('--bracket-columns'); $('.round-labels').innerHTML='<span>Round 1</span><span>Round 2</span><span>Round 3</span>'; const rounds=data.rotation.rounds; $('#bracketGrid').className='bracket-grid rotation-progress'; $('#bracketGrid').style.removeProperty('--bracket-columns'); $('#bracketGrid').innerHTML=[1,2,3].map(number=>{ const round=rounds[number-1]; if(!round)return `<div class="rotation-round-card pending-round"><p>ROUND ${number}</p><h3>Waiting for round ${number-1}</h3><span>Players regroup by league placing.</span></div>`; return `<div class="rotation-round-card"><p>ROUND ${number}</p><h3>${number===1?'Random groups':number===2?'Placement groups':'Final regroup'}</h3>${round.groups.map(group=>`<div class="rotation-group"><b>${group.name}</b>${rotationRoundScores(round,group).map((row,index)=>`<span>${number>1?`${index+1}. `:''}${row.player.name}</span>`).join('')}</div>`).join('')}</div>`; }).join('');
}
function renderRole(){ const pill=$('#rolePill'); const admin=data.role==='admin'; pill.className=`role-pill ${admin?'admin':'visitor'}`; pill.innerHTML=`<span></span> ${admin?'Organiser':'Viewer'}`; $('#adminButton').textContent=admin?'Control room':'Admin access'; }
function renderRequests(){ const pending=data.requests.filter(r=>r.status==='pending'); $('#requestBadge').textContent=pending.length; $('#requestsPanel').innerHTML=pending.length?pending.map(r=>`<div class="request-row"><div class="request-person"><span class="request-initials">${initials(r.name)}</span><div><strong>${r.name}</strong><span>${r.team||'No pair selected'} · requested score access</span></div></div><div class="request-buttons"><button class="small-button" data-deny="${r.id}">Decline</button><button class="small-button approve" data-approve="${r.id}">Approve</button></div></div>`).join(''):`<p class="empty-requests">No scorekeeper requests waiting for you.</p>`; $$('[data-approve]').forEach(b=>b.onclick=()=>{const r=data.requests.find(x=>x.id===b.dataset.approve);r.status='approved';data.approved.push(r.name.toLowerCase());save();renderAll();toast(`${r.name} can now record scores.`)}); $$('[data-deny]').forEach(b=>b.onclick=()=>{data.requests.find(x=>x.id===b.dataset.deny).status='declined';save();renderRequests();}); }
function canEdit(){return data.role==='admin'||(data.scorerName&&data.approved.includes(data.scorerName.toLowerCase()))}
function renderTeamsSelect(){ const choices=isRotation()?data.players.map(person=>person.name):data.teams.map(t=>t.name); $('#requestTeam').innerHTML='<option value="">Choose '+(isRotation()?'your name':'a pair')+'</option>'+choices.map(choice=>`<option>${choice}</option>`).join(''); }
function renderTournamentMeta(){ $('#eventName').textContent=data.tournament.name; $('#eventDate').textContent=data.tournament.date; $('#eventVenue').textContent=data.tournament.venue; if(isRotation()){ const groupSizes=data.rotation.groupSizes||data.rotation.rounds[0].groups.map(group=>group.playerIds.length), groupCount=groupSizes.length, exactThree=groupSizes.every(size=>size%4===0), groupText=groupSizes.join(' / '); $('#heroDescription').textContent=`${data.players.length} players rotate partners in ${groupCount} balanced groups (${groupText} players), matched by experience level.`; $('#formatGuideTitle').innerHTML='Rotate. Rank.<br />Regroup.'; $('#formatGuideSteps').innerHTML=`<li><b>01</b><span>Experience levels are balanced across groups of ${groupText} players.</span></li><li><b>02</b><span>${exactThree?'Every player gets exactly three doubles games each round.':'Groups with 5+ players use a fair 3–4 game rotation.'}</span></li><li><b>03</b><span>Total points after round three decide the podium.</span></li>`; }else{ const qualifierCount=data.teams.length>=8?8:data.teams.length>=4?4:2; $('#heroDescription').textContent=`${data.teams.length} fixed pairs play balanced round-robin league groups before the top ${qualifierCount} contest the knockout stage.`; $('#formatGuideTitle').innerHTML='League play to<br />the podium.'; $('#formatGuideSteps').innerHTML=`<li><b>01</b><span>${data.teams.length} pairs play everyone in their league group.</span></li><li><b>02</b><span>League results seed the top ${qualifierCount} pairs.</span></li><li><b>03</b><span>Win the knockout rounds to lift it.</span></li>`; } }
function renderRules(){ if(isRotation()){const groupSizes=data.rotation.groupSizes||data.rotation.rounds[0].groups.map(group=>group.playerIds.length);$('#formatRuleTitle').textContent='Rotate, rank, regroup';$('#formatRuleText').textContent='Players are balanced by experience into groups of at least four. Groups divisible by four give everyone three games; a five-player group uses a rotating fourth game so no one is left out. The top 3 are decided by total points.';$('#quickFormatRuleTitle').textContent='Balanced rotations';$('#quickFormatRuleText').textContent=`Experience-aware groups of ${groupSizes.join(' / ')} keep games varied and friendly across all three rounds.`;}else{$('#formatRuleTitle').textContent='Play your league';$('#formatRuleText').textContent=`${data.teams.length} fixed pairs play a round robin within balanced league groups before the suitable knockout stage begins.`;$('#quickFormatRuleTitle').textContent='Play your league';$('#quickFormatRuleText').textContent=`${data.teams.length} fixed pairs play round-robin fixtures before the knockout stage.`;} }
function renderAll(){renderTournamentMeta();renderNext();renderStats();renderFixtures();renderStandings();renderBracket();renderRole();renderRules();renderRequests();}
function toast(message){const el=$('#toast');el.textContent=message;el.classList.add('show');setTimeout(()=>el.classList.remove('show'),3500)}
function playerInitials(name){ return name.trim().split(/\s+/).map(word=>word[0]||'').join('').slice(0,2).toUpperCase() || 'DB'; }
function displayDate(value){ const date=new Date(`${value}T12:00:00`); return Number.isNaN(date.valueOf())?'Tournament day':`${date.toLocaleDateString(undefined,{weekday:'long',day:'numeric',month:'long'})} · 09:00`; }
function fixedPoolCount(teamCount){ return teamCount<=4?1:Math.ceil(teamCount/4); }
function generatedMatches(teams){ const matches=[]; const pools=[...new Set(teams.map(t=>t.pool))]; pools.forEach(pool=>{ const members=teams.filter(t=>t.pool===pool); for(let first=0;first<members.length;first++)for(let second=first+1;second<members.length;second++){ const slot=Math.floor(matches.length/4), minutes=9*60+slot*75, time=`${String(Math.floor(minutes/60)).padStart(2,'0')}:${String(minutes%60).padStart(2,'0')}`; matches.push({id:`m${matches.length+1}`,pool,court:`Court ${(matches.length%4)+1}`,time,a:members[first].id,b:members[second].id,status:'upcoming',games:[]}); }}); return matches; }
function playerCountForBuilder(format){ const requested=Number($('#newPlayerCount')?.value), step=format==='rotation'?1:2; if(!Number.isInteger(requested)||requested<4)return 4; return requested-((requested-4)%step); }
function renderPairInputs(format=$('#newFormat')?.value||'teams'){
  const rotation=format==='rotation', countInput=$('#newPlayerCount'), playerCount=playerCountForBuilder(format), pairCount=playerCount/2, rotationGroups=rotation?rotationGroupSizes(playerCount):[], groupCount=rotation?rotationGroups.length:fixedPoolCount(pairCount); countInput.min='4'; countInput.removeAttribute('max'); countInput.step=rotation?'1':'2'; $('#playerCountHint').textContent=rotation?'Rotation League accepts every whole-number player count from 4 upward.':'Fixed doubles needs an even number of players.'; $('#playerBuilderTitle').textContent=rotation?'Your rotation players':'Your fixed doubles pairs'; $('#playerCountLabel').textContent=`${playerCount} players`; $('#newTournamentIntro').textContent=rotation?`Add ${playerCount} individual players. Their experience levels are balanced across ${groupCount} groups of ${rotationGroups.join(' / ')} for three scoring rounds.`:`Add ${pairCount} fixed pairs (${playerCount} players). The app balances them across ${groupCount} league ${groupCount===1?'group':'groups'}, creates round-robin fixtures, and seeds the suitable knockout draw.`; $('#formatBuilderHelp').textContent=rotation?`Enter any whole number of players from 4 upward. The scheduler builds balanced groups of at least four (for example, 14 players become 4 / 5 / 5) and generates fair doubles rotations.`:`Fixed doubles needs an even number of players. Enter both players for each pair; groups stay as even as possible.`;
  $('#playerPairs').classList.toggle('rotation-player-grid',rotation); $('#playerPairs').innerHTML=rotation?Array.from({length:playerCount},(_,index)=>`<label class="rotation-player-input"><span>PLAYER ${String(index+1).padStart(2,'0')}</span><input data-rotation-player="${index}" type="text" maxlength="30" autocomplete="name" placeholder="Player name" required /><select data-rotation-level="${index}" aria-label="Experience level for player ${index+1}"><option value="beginner">Beginner</option><option value="intermediate" selected>Intermediate</option><option value="advanced">Advanced</option><option value="competitive">Competitive</option></select></label>`).join(''):Array.from({length:pairCount},(_,index)=>`<div class="pair-input-row"><div class="pair-number"><b>${String(index+1).padStart(2,'0')}</b><span>Group ${poolLabel(index%groupCount)}</span></div><label>Player 1<input data-player="${index}-a" type="text" maxlength="30" autocomplete="name" placeholder="First player" required /></label><label>Player 2<input data-player="${index}-b" type="text" maxlength="30" autocomplete="name" placeholder="Second player" required /></label></div>`).join('');
}
function openNewTournament(){
  $('#newFormat').value='teams'; $('#newPlayerCount').value='16'; renderPairInputs('teams'); $('#newEventName').value=''; $('#newEventVenue').value=''; $('#newEventDate').value=new Date().toISOString().slice(0,10); $('#newTournamentMessage').textContent=''; $('#dashboardDialog').close(); $('#newTournamentDialog').showModal();
}
function openScore(id){ const m=isRotation()?rotationMatchDetails(id):data.matches.find(match=>match.id===id); if(!canEdit()){editingMatchId=id; $('#accessMessage').textContent=''; $('#accessDialog').showModal(); return;} editingMatchId=id; $('#scoreMatchTitle').textContent=isRotation()?`${rotationPair(m.a)} vs ${rotationPair(m.b)}`:`${team(m.a).name} vs ${team(m.b).name}`; $('#scoreTeams').textContent=isRotation()?`Round ${m.round} · ${m.group} · Group game ${m.slot}`:`${m.court} · Pool ${m.pool} · ${m.time}`; $('#scoreFormatHint').textContent='Record one game to 21 points. The higher score wins the match.'; $('#game2Field').classList.add('hidden'); $('#game3Field').classList.add('hidden'); const fields=$$('#scoreForm input[type=number]'); fields.forEach((f,i)=>f.value=m.games[Math.floor(i/2)]?.[i%2]??''); $('#scoreMessage').textContent=''; $('#scoreDialog').showModal(); }
$('#requestAccessButton').onclick=()=>{$('#accessMessage').textContent='';$('#accessDialog').showModal();};
$('#accessForm').addEventListener('submit',e=>{e.preventDefault();const name=$('#requestName').value.trim();if(!name)return;data.scorerName=name;const previous=data.requests.find(r=>r.name.toLowerCase()===name.toLowerCase());if(data.approved.includes(name.toLowerCase())){$('#accessDialog').close();toast('You already have approval — you can update scores.');renderAll();return;}if(previous){$('#accessMessage').textContent='Your request is already waiting for approval.';return;}data.requests.push({id:Date.now().toString(),name,team:$('#requestTeam').value,status:'pending'});save();$('#accessMessage').textContent='Request sent. Ask the organiser to approve it.';renderRequests();});
$('#adminButton').onclick=()=>{if(data.role==='admin'){$('#dashboardDialog').showModal();return;}$('#adminPasscode').value='';$('#adminMessage').textContent='';$('#adminDialog').showModal();};
$('#adminForm').addEventListener('submit',e=>{e.preventDefault();if($('#adminPasscode').value==='rallyadmin'){data.role='admin';save();$('#adminDialog').close();renderAll();$('#dashboardDialog').showModal();toast('Organiser dashboard unlocked.');}else $('#adminMessage').textContent='That passcode is not right. Try again.';});
$('#dashboardClose').onclick=()=>$('#dashboardDialog').close(); $('#logOutButton').onclick=()=>{data.role='visitor';save();$('#dashboardDialog').close();renderAll();toast('Signed out of organiser mode.');};
$$('.dash-tab').forEach(b=>b.onclick=()=>{$$('.dash-tab').forEach(x=>x.classList.toggle('active',x===b));$('#requestsPanel').classList.toggle('hidden',b.dataset.dash!=='requests');$('#settingsPanel').classList.toggle('hidden',b.dataset.dash!=='settings');});
$('#resetButton').onclick=()=>{if(confirm('Reset all score and access-request data to the demo state?')){data=structuredClone(DEFAULT_DATA);save();$('#dashboardDialog').close();renderAll();toast('Demo tournament reset.')}};
$('#newTournamentButton').onclick=openNewTournament;
$('#newTournamentCancel').onclick=()=>$('#newTournamentDialog').close();
$('#newFormat').onchange=()=>renderPairInputs($('#newFormat').value);
$('#newPlayerCount').addEventListener('input',()=>renderPairInputs($('#newFormat').value));
$('#newTournamentForm').addEventListener('submit',e=>{
  e.preventDefault(); const name=$('#newEventName').value.trim(), venue=$('#newEventVenue').value.trim(), date=$('#newEventDate').value, format=$('#newFormat').value, playerCount=Number($('#newPlayerCount').value);
  if(!name||!venue||!date){$('#newTournamentMessage').textContent='Please add the tournament name, date, and venue.';return;}
  const role=data.role;
  if(format==='rotation'){
    if(!Number.isInteger(playerCount)||playerCount<4){$('#newTournamentMessage').textContent='Rotation League supports every whole-number player count from 4 upward.';return;}
    const names=$$('[data-rotation-player]').map(input=>input.value.trim()), levels=$$('[data-rotation-level]').map(input=>input.value); if(names.length!==playerCount||names.some(value=>!value)){ $('#newTournamentMessage').textContent=`Please enter all ${playerCount} player names.`;return; } if(levels.length!==playerCount||levels.some(level=>!EXPERIENCE_SCORE[level])){$('#newTournamentMessage').textContent='Choose an experience level for every player.';return;} if(new Set(names.map(value=>value.toLowerCase())).size!==names.length){$('#newTournamentMessage').textContent='Each player name must be unique.';return;}
    if(!confirm(`Create “${name}”? This will replace the current tournament, results, and scorekeeper approvals.`)) return;
    const rotationPlayers=names.map((person,index)=>({id:`p${index+1}`,name:person,experience:levels[index]})), groupSizes=rotationGroupSizes(playerCount), equalGroups=balancedRotationGroups(rotationPlayers,groupSizes); data={tournament:{name,venue,date:displayDate(date),format:'rotation'},teams:[],matches:[],players:rotationPlayers,rotation:{groupSizes,rounds:[buildRotationRound(1,equalGroups)]},requests:[],approved:[],role,scorerName:''};
  } else {
    if(!Number.isInteger(playerCount)||playerCount<4||playerCount%2!==0){$('#newTournamentMessage').textContent='Fixed doubles needs an even number of at least 4 players.';return;}
    const pairInputs=$$('#playerPairs input'),pairs=[]; for(let i=0;i<pairInputs.length;i+=2){const first=pairInputs[i].value.trim(),second=pairInputs[i+1].value.trim();if(!first||!second){$('#newTournamentMessage').textContent='Please enter both players for every pair.';return;}pairs.push([first,second]);} const allNames=pairs.flat(); if(pairs.length!==playerCount/2){$('#newTournamentMessage').textContent='Player entries do not match the selected count.';return;} if(new Set(allNames.map(value=>value.toLowerCase())).size!==allNames.length){$('#newTournamentMessage').textContent='Each player name must be unique.';return;}
    if(!confirm(`Create “${name}”? This will replace the current tournament, results, and scorekeeper approvals.`)) return;
    const groupCount=fixedPoolCount(pairs.length), teams=pairs.map(([first,second],index)=>({id:`t${index+1}`,name:`${first} & ${second}`,short:`${playerInitials(first)}${playerInitials(second)}`.slice(0,4),players:`${first} · ${second}`,pool:poolLabel(index%groupCount)})); data={tournament:{name,venue,date:displayDate(date),format:'teams'},teams,matches:generatedMatches(teams),players:[],rotation:null,requests:[],approved:[],role,scorerName:''};
  }
  activePool='A';activeFilter='all';save();$('#newTournamentDialog').close();renderTeamsSelect();renderAll();window.scrollTo({top:0,behavior:'smooth'});toast(`${name} is ready to play.`);
});
$('#scoreForm').addEventListener('submit',e=>{e.preventDefault();const m=isRotation()?rotationMatchById(editingMatchId):data.matches.find(match=>match.id===editingMatchId);const vals=$$('#scoreForm input[type=number]').map(f=>f.value===''?null:Number(f.value));const games=[];for(let i=0;i<3;i++){if(vals[i*2]!==null&&vals[i*2+1]!==null)games.push([vals[i*2],vals[i*2+1]]);}if(games.length<1){$('#scoreMessage').textContent='Please record the game score.';return;}const aGames=games.filter(([a,b])=>a>b).length,bGames=games.filter(([a,b])=>b>a).length;if(aGames===bGames){$('#scoreMessage').textContent='The result needs a winning pair.';return;}m.games=[games[0]];m.status='complete';const nextRound=isRotation()?advanceRotation():null;save();$('#scoreDialog').close();renderAll();toast(nextRound?`Round ${nextRound.number} groups are ready.`:'Match result saved — standings updated.');});
$$('.pool-toggle-btn').forEach(b=>b.onclick=()=>{activePool=b.dataset.pool;$$('.pool-toggle-btn').forEach(x=>x.classList.toggle('active',x===b));renderStandings();});
$$('.filter-tab').forEach(b=>b.onclick=()=>{activeFilter=b.dataset.filter;$$('.filter-tab').forEach(x=>x.classList.toggle('active',x===b));renderFixtures();});
$$('[data-view]').forEach(b=>b.onclick=()=>{const target=$('#'+b.dataset.view);target.scrollIntoView({behavior:'smooth',block:'start'});$$('[data-view]').forEach(x=>x.classList.toggle('active',x===b));});
$$('[data-scroll]').forEach(b=>b.onclick=()=>$('#'+b.dataset.scroll).scrollIntoView({behavior:'smooth',block:'start'}));
$$('[data-view-target]').forEach(b=>b.onclick=()=>$('#'+b.dataset.viewTarget).scrollIntoView({behavior:'smooth',block:'start'}));
setInterval(()=>{$('#clock').textContent=new Date().toLocaleTimeString([],{hour:'2-digit',minute:'2-digit'});},1000);
renderTeamsSelect();renderAll();
